### ISSUE TITLE
ValueError in example

### ISSUE THREAD

**Issue by bborozan** [euxhenh/phenotype-cover#1]
I tried using your method but running the example code provided in the readme,  
```
X = np.log1p(np.random.randint(0, 1000, (1000, 200)))
y = np.random.randint(0, 5, 1000)
gpc = GreedyPC()
gpc.fit(X, y)
features = gpc.select(100)
```

produces the following error: 
```
Traceback (most recent call last):
  File ".../gpc_test.py", line 17, in <module>
    features = gpc.select(100)
  File ".../.local/lib/python3.10/site-packages/phenotype_cover/_phenotype_cover.py", line 169, in select
    self.multiplier = self._multiplier
  File ".../.local/lib/python3.10/site-packages/phenotype_cover/_phenotype_cover.py", line 291, in multiplier
    self._gci_wrapper.fit(self.M_)
  File ".../.local/lib/python3.10/site-packages/phenotype_cover/_gci_wrapper.py", line 98, in fit
    raise ValueError(
ValueError: No sets were selected. This means your data matrix consists of only zeros. Please use higher multiplicity.
```
Python version 3.10 on Ubuntu Ubuntu 22.04.2 LTS.

Could You please help me with this issue?

Thank You in advance,
Bartol

**Comment by euxhenh** [comment]
Hi,

Thank you for pointing this out. It looks like this way of randomly generating the data leads to a pairwise matrix M that consists of zeros with high probability, hence, the error.

Here's a better way to generate random data using scikit-learn.
```
from sklearn.datasets import make_classification

X, y = make_classification(1000, 200, n_informative=5, n_classes=5, scale=100)
gpc = GreedyPC()
gpc.fit(X, y)
features = gpc.select(10)
```

I will update the docs ASAP.

Thank you!

I am closing the issue.
